meta:
  run_name: "default_ppo"
  version: "1.0.0"

algo: PPO
policy: MlpPolicy
device: cuda
render_mode: null

env:
  duck_speed: 1.0
  wolf_speed: 2.0

training:
  n_envs: 4
  total_timesteps: 1_000_000

log:
  verbose: 1

hyperparameters:
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  gamma: 0.99
  reward_scale: 1.0
