run_name: run_SAC_big

model_path: models\saved_model

render_mode: None

log:
  verbose: 1

algo: 'SAC'

policy: 'MlpPolicy'

training:
  total_timesteps: 2_000_000
  n_envs: 1

device: cuda

hyperparameters:
  learning_rate: 3.e-4
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  ent_coef: 'auto'
  target_entropy: 'auto'
  learning_starts: 10_000
  buffer_size: 500_000
  train_freq: 1
  gradient_steps: 1
  reward_scale: 1.0